spring:
  datasource:
    url: ENC(uO8kwbE0bFZ6DSMC+wmi3UnrkYveaDKVnL6bWLImoO4IsJTaWhWkRtVelBzR25bTaHFwOc5fXIaIyZKiACYe0lBCc6coTTCOFHrP3NyBzZUQpIXmiLIfmg==)
    username: ENC(Rs2ms76oQ1z8zM0GAoa/AA==)
    password: ENC(dvvMUaXEaPDiS2pzIgWo0SARQOuUsAulD5Pjjdvo2z8=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
