spring:
  datasource:
    url: jdbc:mysql://withyou-db.ctgu806wcu3i.ap-northeast-1.rds.amazonaws.com/with_you
    username: withYou
    password: withYouServerDudwo1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
