server:
  port: 8080
  #servlet:
  #context-path: /api
spring:
  profiles:
    active: dev, oauth
  datasource:
    hikari:
      minimum-idle: 22
      maximum-pool-size: 22
  data:
    redis:
      host: ENC(BmVFNh6evAsOpejjYfA35Q==)
      port: 6379

jwt:
  secret: ENC(7bmxJEYMUVIrgCM+TkClZaX2DDLqzKTO6Jp9C1fZg5a/aPvxz4tPpbbzF2cUqyjDJ3nThdVqepw=)
  expiration-period: ENC(rhU/5h9od5+FKCuh5iIeJA==)
  header: ENC(i+cGKdSqtE6rebBZswksr1Uu9O58DNYx)
  prefix: ENC(U+nfPN7QOj1ohWCXahSheA==)
  refresh:
    expiration-period: ENC(DpdQuzNXc24kB4v0qJkDUA==)

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

cloud:
  aws:
    s3:
      bucket: ENC(PL3eeYTb8i9ifHB0csm1HrOMxGJUy31Q)
    stack.auto: false
    region.static: ENC(0qcAVhglKAkgkKAkH4LJZzr9Gnl9ZuhA)
    credentials:
      accessKey: ENC(LYSekTBrws9Ru1VLVtdbadnRb3n8IYf6pJqpTv3IpOo=)
      secretKey: ENC(vYct9ku08uS4w0OfDsdAhY8kZLrPoAMvh2AdzEY6OMFioByGHXcFafAUEeU7ZuFpuidpJn3cNNA=)