name: backend CI Config

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
      
permissions:
  pull-requests: write
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: ✨ JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: ✨ Gradle 의존성 캐싱
        uses: actions/cache@v3
        with:
          path: |  
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
              
      - name: ✨ Gradlew 권한 설정
        run: chmod +x ./gradlew
        working-directory: ${{ env.working-directory }}

      - name: ✨ 테스트 진행
        run: ./gradlew test
        working-directory: ${{ env.working-directory }}

      - name: ✨ 테스트 결과 Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}
        with:
          files: '**/build/test-results/**/*.xml'
