name: Backend CD Config

on:
  pull_request:
    branches:
      - develop
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/with-you:latest
            docker stop with-you-container || true
            docker rm with-you-container || true
            docker run -d -p 8080:8080 \
              -e ENCRYPT_KEY=${{ secrets.ENCRYPT_KEY }} \
              --network WithYou-network \
              --name with-you-container \
              835354238306.dkr.ecr.ap-northeast-1.amazonaws.com/with-you:latest